spring.application.name=signe-backend

# ===== Datasource - H2 persistente em arquivo =====
spring.datasource.url=jdbc:h2:file:./data/signe;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===== JPA / Hibernate =====
spring.jpa.database=h2
spring.jpa.properties.hibernate.type.preferred_uuid_TypeCode=VARCHAR
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.id.generator.preferred_uuid_encodings=STRING
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===== Console H2 (interface web para inspecionar as tabelas) =====
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console